image: alpine

stages:
  - env-setup
  - compile
  - test
  - deploy

env-setup:
  image: golang
  stage: env-setup
  variables:
    TEST: test
  only:
    - main
  script:
    - echo test

compile:
  image: golang
  stage: compile
  variables:
    TEST: test
  only:
    - main
  script:
    - echo test

test:
  image: golang
  stage: test
  variables:
    TEST: test
  only:
    - main
  script:
    - echo test

deploy-local:
  image: golang
  stage: deploy
  variables:
    TEST: test
  allow_failure: false
  only:
    - main
  script:
    - echo test

deploy-testnet:
  image: go
  stage: deploy
  when: manual
  allow_failure: false
  variables:
    TEST: test
  only:
    - main
  script:
    - echo test

deploy-mainnet:
  image: go
  stage: deploy
  when: manual
  allow_failure: false
  variables:
    TEST: test
  only:
    - main
  script:
    - echo test
